/**
 * Generator — the mechanism (plans/codegen-api-sketch.md §4).
 *
 * Reads a consumer's cldr.config.ts, validates it against the runtime's
 * hand-authored manifest, and emits a literal cldr.gen.ts: static imports
 * of exactly the selected methods + transitive modules + the configured
 * locale packs. Tree-shaking becomes a property of what is emitted — the
 * bundler only ever sees reachable code. Unselected slots are absent, so
 * the consumer's strict tsc never trips on unused generated imports.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { manifest } from '@phensley/cldr/manifest';
import type { FeatureManifest, MethodRef } from '@phensley/cldr/manifest';
import { layout as rawLayout } from '@phensley/cldr/packs/layout';

/**
 * Family layout (generated by generate-packs, design doc §3 row 2): per
 * tag, whether a full pack module or a base+delta composition ships.
 * The generator's config-scoped selection decides per CONFIG shape.
 */
type LayoutEntry = { kind: 'full' } | { kind: 'delta'; base: string };
const layout = rawLayout as Record<string, LayoutEntry>;

/** Module + export name for a tag's pack data under a given layout. */
const packModule = (tag: string, useDelta: boolean): { module: string; name: string } => {
  const stem = tag.replace(/[^a-zA-Z0-9]/g, '');
  return useDelta
    ? { module: `@phensley/cldr/packs/delta/${stem}`, name: stem }
    : { module: `@phensley/cldr/packs/${stem}`, name: stem };
};

// ---------------------------------------------------------------------------
// config surface (consumer-authored, cldr.config.ts)

export interface LazyLocales {
  lazy: true;
}

export type LocalesConfig = readonly string[] | LazyLocales;

/** boolean = whole slot; nested object = per-namespace-slot selection. */
export type FeatureConfig = boolean | Record<string, boolean | Record<string, boolean>>;

export interface CldrConfig {
  locales: LocalesConfig;
  features: Record<string, FeatureConfig>;
}

/** Typed identity: the only import a consumer's config file needs. */
export const defineConfig = <C extends CldrConfig>(config: C): C => config;

// ---------------------------------------------------------------------------
// selection resolution

type SlotTree = Record<string, { namespace?: Record<string, MethodRef>; ref?: MethodRef }>;

interface ResolvedFeature {
  tree: SlotTree;
  refs: MethodRef[];
}

const validFeatureSlots = (fm: FeatureManifest): string[] =>
  Object.entries(fm.slots).map(([k, v]) => ('namespace' in v ? `${k}.${Object.keys(v.namespace).join('/')}` : k));

const resolveFeature = (feature: string, fm: FeatureManifest, selection: FeatureConfig): ResolvedFeature => {
  const tree: SlotTree = {};
  const refs: MethodRef[] = [];
  const addNamespace = (key: string, ns: Record<string, MethodRef>) => {
    tree[key] = { namespace: { ...ns } };
    refs.push(...Object.values(ns));
  };
  if (selection === true) {
    for (const [key, slot] of Object.entries(fm.slots)) {
      if ('namespace' in slot) {
        addNamespace(key, slot.namespace);
      } else {
        tree[key] = { ref: slot };
        refs.push(slot);
      }
    }
    return { tree, refs };
  }
  for (const [key, chosen] of Object.entries(selection)) {
    const slot = fm.slots[key];
    if (slot === undefined) {
      throw new Error(`feature "${feature}": unknown selection "${key}" (valid: ${validFeatureSlots(fm).join(', ')})`);
    }
    if ('namespace' in slot) {
      if (chosen === true) {
        addNamespace(key, slot.namespace);
      } else if (typeof chosen === 'object') {
        const ns: Record<string, MethodRef> = {};
        for (const [nk, v] of Object.entries(chosen)) {
          const ref = slot.namespace[nk];
          if (ref === undefined) {
            throw new Error(`feature "${feature}": unknown selection "${key}.${nk}" (valid: ${key}.${Object.keys(slot.namespace).join('/')})`);
          }
          if (v === true || typeof v === 'object') {
            ns[nk] = ref;
          }
        }
        addNamespace(key, ns);
      }
    } else if (chosen === true) {
      tree[key] = { ref: slot };
      refs.push(slot);
    } else {
      throw new Error(`feature "${feature}": selection "${key}" must be boolean (valid: ${validFeatureSlots(fm).join(', ')})`);
    }
  }
  return { tree, refs };
};

// ---------------------------------------------------------------------------
// emission

export const HEADER = '// Generated by @phensley/cldr-generate — do not edit. Regenerate with pnpm generate:client.\n';

const renderTree = (tree: SlotTree, indent: string, localOf: Map<MethodRef, string>): string => {
  const parts: string[] = [];
  for (const [key, node] of Object.entries(tree)) {
    if (node.ref !== undefined) {
      parts.push(`${indent}${key}: ${localOf.get(node.ref) ?? node.ref.exportName},`);
    } else if (node.namespace !== undefined) {
      const inner = Object.entries(node.namespace)
        .map(([k, r]) => `${k}: ${localOf.get(r) ?? r.exportName}`)
        .join(', ');
      parts.push(`${indent}${key}: { ${inner} },`);
    }
  }
  return `{\n${parts.join('\n')}\n${indent.slice(0, -2)}}`;
};

const renderInline = (tree: SlotTree, localOf: Map<MethodRef, string>): string => {
  const parts = Object.entries(tree).map(([key, node]) =>
    node.ref !== undefined
      ? `${key}: ${localOf.get(node.ref) ?? node.ref.exportName}`
      : `${key}: { ${Object.entries(node.namespace!).map(([k, r]) => `${k}: ${localOf.get(r) ?? r.exportName}`).join(', ')} }`,
  );
  return `{ ${parts.join(', ')} }`;
};

export const generate = (config: CldrConfig): string => {
  const lazy = typeof config.locales === 'object' && 'lazy' in config.locales;
  const localeTags = lazy ? [...manifest.locales] : [...(config.locales as readonly string[])];
  for (const tag of localeTags) {
    if (!manifest.locales.includes(tag as (typeof manifest.locales)[number])) {
      throw new Error(`locale "${tag}" has no runtime pack (available: ${manifest.locales.join(', ')})`);
    }
  }

  // -- family layout selection (eager): a family is ACTIVE when ≥2
  // configured locales share a base (variants + the base itself). Active
  // variants ship their delta module; the base ships once (extra import
  // when the base itself is not configured). Lone variants and
  // cross-family locales stay full literals.
  const configured = new Set(localeTags);
  const variantCount = new Map<string, number>();
  for (const tag of localeTags) {
    const e = layout[tag];
    if (e !== undefined && e.kind === 'delta') {
      variantCount.set(e.base, (variantCount.get(e.base) ?? 0) + 1);
    }
  }
  const activeVariants = new Set<string>(); // configured tags that use their delta
  const activeBases = new Set<string>();
  for (const tag of localeTags) {
    const e = layout[tag];
    if (e !== undefined && e.kind === 'delta') {
      const familySize = (variantCount.get(e.base) ?? 0) + (configured.has(e.base) ? 1 : 0);
      if (familySize >= 2) {
        activeVariants.add(tag);
        activeBases.add(e.base);
      }
    }
  }
  for (const base of activeBases) {
    if (!manifest.locales.includes(base as (typeof manifest.locales)[number])) {
      throw new Error(`family base "${base}" has no runtime pack`);
    }
  }

  // resolve + validate features against the manifest
  const resolved = new Map<string, ResolvedFeature>();
  let localeFeature = false;
  let usesCalendar = false;
  const factories = new Set<string>();
  for (const [feature, selection] of Object.entries(config.features)) {
    const fm = manifest.features[feature];
    if (fm === undefined) {
      throw new Error(`unknown feature "${feature}" (valid: ${Object.keys(manifest.features).join(', ')})`);
    }
    const r = resolveFeature(feature, fm, selection);
    if (r.refs.length > 0) {
      resolved.set(feature, r);
      factories.add(fm.factory);
      localeFeature = localeFeature || fm.needsLocaleData;
      usesCalendar = usesCalendar || fm.factory === 'makeCalendarFactory';
    }
  }
  if (resolved.size === 0) {
    throw new Error('config selects no features');
  }

  // dedupe method refs across features, deterministic order
  const seen = new Set<string>();
  const refs: MethodRef[] = [];
  for (const r of resolved.values()) {
    for (const ref of r.refs) {
      const key = `${ref.specifier}#${ref.exportName}`;
      if (!seen.has(key)) {
        seen.add(key);
        refs.push(ref);
      }
    }
  }
  refs.sort((a, b) => (a.specifier < b.specifier ? -1 : a.specifier > b.specifier ? 1 : 0));

  // distinct features may export the same name (currency/format vs
  // calendar/format): the generated client aliases colliding exports
  // per-REF local names: colliding export names (currency/format vs
  // calendar/format) get distinct aliases
  const localOf = new Map<MethodRef, string>();
  const nameCounts = new Map<string, number>();
  for (const ref of refs) {
    const n = nameCounts.get(ref.exportName) ?? 0;
    nameCounts.set(ref.exportName, n + 1);
    localOf.set(ref, n === 0 ? ref.exportName : `${ref.exportName}$${n}`);
  }

  const lines: string[] = [HEADER];
  const runtime = ['createCldr', ...[...factories].sort()];
  lines.push(`import { ${runtime.join(', ')} } from '@phensley/cldr';`);
  if (lazy) {
    lines.push("import type { Cldr } from '@phensley/cldr';");
  }
  for (const ref of refs) {
    const local = localOf.get(ref)!;
    lines.push(local === ref.exportName ? `import { ${ref.exportName} } from '${ref.specifier}';` : `import { ${ref.exportName} as ${local} } from '${ref.specifier}';`);
  }

  for (const [feature, r] of resolved) {
    if (manifest.features[feature].factory === 'makeDecimalFactory') {
      lines.push('', `const ${feature} = makeDecimalFactory(${renderTree(r.tree, '  ', localOf)});`);
    }
  }

  const usePacks = localeFeature;
  if (usePacks) {
    lines.push('', 'import type { DecodedLocalePack } from \'@phensley/cldr\';');
    if (!lazy) {
      // eager imports: configured locales + extra family bases, deduped
      const imports = new Map<string, string>(); // module → name
      for (const tag of localeTags) {
        const useDelta = activeVariants.has(tag);
        const { module, name } = packModule(tag, useDelta);
        imports.set(module, name);
      }
      for (const base of [...activeBases].sort()) {
        if (!configured.has(base)) {
          const { module, name } = packModule(base, false);
          imports.set(module, name);
        }
      }
      for (const [module, name] of [...imports.entries()].sort(([a], [b]) => (a < b ? -1 : 1))) {
        lines.push(`import { ${name} } from '${module}';`);
      }
    }
  }

  // calendar: the shared zone-offset companion is captured at module scope
  if (usesCalendar) {
    lines.push(
      "import { zones as zonesPack } from '@phensley/cldr/packs/zones';",
      "import { decodeZonesTable } from '@phensley/cldr';",
      'const zonesTable = decodeZonesTable(zonesPack);',
    );
  }

  const buildParts: string[] = [];
  for (const [feature, r] of resolved) {
    const factory = manifest.features[feature].factory;
    if (factory === 'makeDecimalFactory') {
      buildParts.push(`${feature},`);
    } else if (factory === 'makePluralFactory') {
      buildParts.push(`${feature}: makePluralFactory(pack!, ${renderInline(r.tree, localOf)}),`);
    } else if (factory === 'makeCalendarFactory') {
      buildParts.push(`${feature}: makeCalendarFactory(pack!, zonesTable, ${renderInline(r.tree, localOf)}),`);
    } else {
      buildParts.push(`${feature}: makeCurrencyFactory(pack!, ${renderInline(r.tree, localOf)}),`);
    }
  }
  const buildParam = usePacks ? '(pack: DecodedLocalePack | undefined)' : '()';
  lines.push('', `const build = ${buildParam} => ({`, ...buildParts.map((p) => `  ${p}`), '});');

  lines.push('', lazy ? 'const client = createCldr({' : 'export const cldr = createCldr({', `  lazy: ${lazy},`, `  locales: ${JSON.stringify(localeTags)} as const,`);
  if (usePacks) {
    // map keys: configured locales + extra family bases (the client
    // resolves deltas' base tags against this map)
    const packKeys = lazy ? localeTags : [...localeTags, ...[...activeBases].filter((b) => !configured.has(b)).sort()];
    const packs = packKeys.map((t) => {
      const useDelta = lazy ? layout[t]?.kind === 'delta' : activeVariants.has(t);
      const { module, name } = packModule(t, useDelta === true);
      return lazy
        ? `${JSON.stringify(t)}: () => import('${module}').then((m) => m.${name})`
        : `${JSON.stringify(t)}: ${name}`;
    });
    lines.push(`  packs: { ${packs.join(', ')} },`);
  }
  lines.push('  build,', '});', '');
  if (lazy) {
    // Lazy mode: locale is an open set at runtime, so the exported client
    // widens the narrowed internal one; unknown tags still throw in
    // resolveLocale with the available list.
    const union = localeTags.map((t) => JSON.stringify(t)).join(' | ');
    lines.push(
      'export const cldr: Cldr<string, ReturnType<typeof build>> = {',
      '  get(locale) {',
      `    return client.get(locale as ${union});`,
      '  },',
      '  preload(locale) {',
      `    return client.preload(locale as ${union});`,
      '  },',
      '};',
      '',
    );
  }
  return lines.join('\n');
};

/** Generate + write the client to disk (CLI/harness path). */
export const writeClient = (config: CldrConfig, out: string): string => {
  const code = generate(config);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, code);
  return code;
};
