/**
 * Generated by scripts/scan-manifest.ts — DO NOT EDIT. Regenerate with pnpm scan:manifest.
 *
 * Derived from the source of truth: the *Api interfaces in src/api.ts (slot surface),
 * the impl modules (each ref verified to exist), factory.ts, and the packs/
 * directory (locales). The package.json exports map is derived from the same
 * run: the runtime's public surface is exactly its slot refs (no wildcard
 * reachability for internals). Per-feature pack-stream metadata is declared
 * in FEATURE_META in the scanner. Freshness is enforced by
 * packages/cldr/__tests__/manifest.test.ts (same pattern as the pack assets).
 */
export interface MethodRef {
  /** Package subpath specifier, e.g. '@phensley/cldr/decimal/compare'. */
  specifier: string;
  /** Named export of that module. */
  exportName: string;
}

export interface NamespaceSlot {
  namespace: Record<string, MethodRef>;
}

export type FeatureSlot = MethodRef | NamespaceSlot;

export interface FeatureManifest {
  /** Config keys → impl refs (true = whole surface / whole namespace). */
  slots: Record<string, FeatureSlot>;
  /** Pack streams this feature reads (informational, per-locale v0). */
  data: string[];
  /** True when the feature needs the locale's decoded pack. */
  needsLocaleData: boolean;
  /** Runtime factory the generated client assembles this feature with. */
  factory: 'makeDecimalFactory' | 'makeCurrencyFactory' | 'makePluralFactory' | 'makeCalendarFactory';
}

export interface Manifest {
  /** Every locale the runtime ships packs for (lazy mode maps ALL of them). */
  locales: readonly string[];
  features: Record<string, FeatureManifest>;
}

export const manifest: Manifest = {
  locales: ['ar', 'de', 'en', 'en-001', 'en-AU', 'en-CA', 'en-GB', 'fr', 'hi', 'ru', 'zh'],
  features: {
    decimal: {
      factory: 'makeDecimalFactory',
      data: [],
      needsLocaleData: false,
      slots: {
        compare: { specifier: '@phensley/cldr/decimal/compare', exportName: 'compare' },
        min: { specifier: '@phensley/cldr/decimal/min', exportName: 'min' },
        max: { specifier: '@phensley/cldr/decimal/max', exportName: 'max' },
        movePoint: { specifier: '@phensley/cldr/decimal/move-point', exportName: 'movePoint' },
        format: {
          namespace: {
            scientific: { specifier: '@phensley/cldr/decimal/format/scientific', exportName: 'scientific' },
          },
        },
      },
    },
    currency: {
      factory: 'makeCurrencyFactory',
      data: ['currencies', 'patterns', 'pool'],
      needsLocaleData: true,
      slots: {
        format: { specifier: '@phensley/cldr/currency/format', exportName: 'format' },
        symbol: { specifier: '@phensley/cldr/currency/symbol', exportName: 'symbol' },
        fractionDigits: { specifier: '@phensley/cldr/currency/fraction-digits', exportName: 'fractionDigits' },
      },
    },
    calendar: {
      factory: 'makeCalendarFactory',
      data: ['calendar'],
      needsLocaleData: true,
      slots: {
        format: { specifier: '@phensley/cldr/calendar/format', exportName: 'format' },
        monthName: { specifier: '@phensley/cldr/calendar/month-name', exportName: 'monthName' },
        weekdayName: { specifier: '@phensley/cldr/calendar/weekday-name', exportName: 'weekdayName' },
        firstDay: { specifier: '@phensley/cldr/calendar/first-day', exportName: 'firstDay' },
        offset: { specifier: '@phensley/cldr/calendar/offset', exportName: 'offset' },
      },
    },
    plural: {
      factory: 'makePluralFactory',
      data: ['plural'],
      needsLocaleData: true,
      slots: {
        select: { specifier: '@phensley/cldr/plural/select', exportName: 'select' },
      },
    },
  },
};
