// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.

import type { LocalePack } from '@cldr/internal-core';
export const de: LocalePack = {
  "pool": {
    "codec": "utf8",
    "offsets": "((((=(((+3,9.c66OG]n=yoI_F*Rf|St5Pj(((((",
    "data": "3`XUcM/wO0HZ{s2>YSr.KPNyLMhgd>IWg1xH;J[QKQV@/Is/oQKPlOuKMvyaJpcO}?u}cPKNMv_H>el|GBe]mBRc-,Jop:tBirE`Gyf.|IuUe{GBelrKOADpHZO+zI=>e4BntN^MJnErH[KFzKQCi1H[Q|mgu`N{I=,X|GyhhZgWW6@M1/}=Lj6zxIeD_M"
  },
  "territories": {
    "trie": "((((r(-Fp]=<U(2=qdB|2GcTL3)^jb?p1YlBJsnQ6Otjl)[gS5(/c6l(_he8(zzR4>7V4()]2u/)^:x3A.2Hx(_hR2*=jI7((Uc-)]d=<,RRL4(((((((((("
  },
  "currencies": {
    "trie": "((((M(*m::>8Bbz?k[L+-tn^W(/c0b*u),/*u1LvAfP<*D]E;)(0(^,Bif[k(((((",
    "table": "((((4((::?(aEKM(((I5((:4*((((("
  },
  "patterns": {
    "codec": "utf8",
    "offsets": "((((,(((CB1C=.E(((((",
    "data": "3As-i7Q;Yx3@vhi3BG(43xVzk3BAh/7b.S)]eAHx"
  }
};
