// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.

import type { LocalePack } from '@cldr/internal-core';
export const de: LocalePack = {
  "pool": [
    "$",
    "Brasilien",
    "CHF",
    "China",
    "Deutschland",
    "Frankreich",
    "Indien",
    "Italien",
    "Japan",
    "Niederlande",
    "Russland",
    "SEK",
    "Schweiz",
    "Spanien",
    "Vereinigte Staaten",
    "Vereinigtes Königreich",
    "£",
    "¥",
    "Österreich",
    "€"
  ],
  "territories": {
    "trie": "((((r(-Fp]=<U(2=qdB|2GcTL3)^jb?p1YlBJsnQ6Otjl)[gS5(/c6l(_he8(zzR4>7V4()]2u/)^:x3A.2Hx(_hR2*=jI7((Uc-)]d=<,RRL4(((((((((("
  },
  "currencies": {
    "trie": "((((M(*m::>8Bbz?k[L+-tn^W(/c0b*u),/*u1LvAfP<*D]E;)(0(^,Bif[k(((((",
    "table": "((((4((::?(aEKM(((I5((:4*((((("
  },
  "patterns": [
    "#,##0.###",
    "#,##0 %",
    "#,##0.00 ¤"
  ]
};
