// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.

import type { LocalePack } from '@cldr/internal-core';
export const en: LocalePack = {
  "pool": [
    "$",
    "Australia",
    "Brazil",
    "CA$",
    "CHF",
    "Canada",
    "China",
    "Côte d’Ivoire",
    "France",
    "Germany",
    "India",
    "Italy",
    "Japan",
    "Russia",
    "Spain",
    "United Kingdom",
    "United States",
    "£",
    "¥",
    "€"
  ],
  "territories": {
    "trie": "((((q(,xWV=<Br.=qdI(3)CmP3a>|f?pCrtCH)M[(LIA0BGa|y(/lBo)@Hb3*=;k6)]Y]+,[CF9*bAoA=;4On(h[;,+:ATC()Bc4,@:XJBbOl|"
  },
  "currencies": {
    "trie": "((((N(*Gx4>8q+.?k[[2/JLN7?4?py(/=|s>S@2zCKr31=BY{s(0Xn0)ePmp(((((",
    "table": "((((4((C@1(aa^P(__q<((:4*((((("
  },
  "patterns": [
    "#,##0.###",
    "#,##0%",
    "¤#,##0.00"
  ]
};
