// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.

import type { LocalePack } from '@cldr/internal-core';
export const fr: LocalePack = {
  "pool": [
    "$US",
    "Allemagne",
    "Brésil",
    "CHF",
    "Chine",
    "Espagne",
    "France",
    "Inde",
    "Italie",
    "Japon",
    "Maroc",
    "Royaume-Uni",
    "Russie",
    "Suisse",
    "£UK",
    "¥",
    "États-Unis",
    "€"
  ],
  "territories": {
    "trie": "((((m(,xZW=W_(6>7)E|1g5BK2H0^e@lquoCGZ5W(hIGz(gzl|()Hz:)[g+y)[^P0**a];=;1en(h[;,*=E08)]Z(6+A2p/(1.8=BbOl|((((("
  },
  "currencies": {
    "trie": "((((G(*Gx4>80Uv?k[F+-5-E4>S@,yCKr30=BY{o)-U33)I5do",
    "table": "((((2((C@>(a3?I((((*(((((((((("
  },
  "patterns": [
    "#,##0.###",
    "#,##0 %",
    "#,##0.00 ¤"
  ]
};
