// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.

import type { NumericPack } from '@cldr/internal-core';

export const numeric: NumericPack = {
  "keys": [
    "UTC-12",
    "UTC-11",
    "UTC-10",
    "UTC-9",
    "UTC-8",
    "UTC-7",
    "UTC-6",
    "UTC-5",
    "UTC-4",
    "UTC-3",
    "UTC-2",
    "UTC-1",
    "UTC",
    "UTC+1",
    "UTC+2",
    "UTC+3",
    "UTC+4",
    "UTC+5",
    "UTC+6",
    "UTC+7",
    "UTC+8",
    "UTC+9",
    "UTC+10",
    "UTC+11",
    "UTC+12",
    "UTC+13",
    "UTC+14",
    "EXTREME",
    "CEILING"
  ],
  "values": "((((Ep}Ntic5)0P(NKT7zzT+b1(7;KWXR9=+r7+-RhB5q)?q@e)L`lU)YOAF)g?da[L`1[0*hc}zzC+("
};
