// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.

import type { NumericPack } from '@cldr/internal-core';

export const numeric: NumericPack = {
  "keys": {
    "codec": "utf8",
    "offsets": "((((F(((::-n9U94:3WT911zo>vhvcCi6{JJ9d;xOd+{:Wig`X",
    "data": "CL0DB7m}i5=Z8*PCL0DB7mk]3=Z8B}C.z<{CL0DB9k_oL6U4]5=Z86yC.z<wCL0DB8RGJH6TfD1=Z8*uC.{aj=Y{tsC.z6sCL0D@8RGJH5tA>1=Y|*wC.z6wCL0D@9k_oL5tfV5=Y|6{C.z6r7UK/E5szjaC.z6r87,AG5szpcC.z6r8l|TNBMVBR=]iYF?W^j]"
  },
  "values": "((((Ep}Ntic5)0P(NKT7zzT+b1(7;KWXR9=+r7+-RhB5q)?q@e)L`lU)YOAF)g?da[L`1[0*hc}zzC+("
};
