// Generated by @phensley/cldr-generate — do not edit. Regenerate with pnpm generate:client.

import { createCldr, makeCurrencyFactory, makeDecimalFactory, makePluralFactory } from '@phensley/cldr';
import { format } from '@phensley/cldr/currency/format';
import { fractionDigits } from '@phensley/cldr/currency/fraction-digits';
import { symbol } from '@phensley/cldr/currency/symbol';
import { compare } from '@phensley/cldr/decimal/compare';
import { scientific } from '@phensley/cldr/decimal/format/scientific';
import { min } from '@phensley/cldr/decimal/min';
import { select } from '@phensley/cldr/plural/select';

const decimal = makeDecimalFactory({
  compare: compare,
  min: min,
  format: { scientific: scientific },
});

import type { DecodedLocalePack } from '@phensley/cldr';
import { ar } from '@phensley/cldr/packs/ar';
import { de } from '@phensley/cldr/packs/de';
import { en } from '@phensley/cldr/packs/delta/en';
import { enGB } from '@phensley/cldr/packs/delta/enGB';
import { en001 } from '@phensley/cldr/packs/en001';
import { fr } from '@phensley/cldr/packs/fr';

const build = (pack: DecodedLocalePack | undefined) => ({
  decimal,
  currency: makeCurrencyFactory(pack!, { format: format, symbol: symbol, fractionDigits: fractionDigits }),
  plural: makePluralFactory(pack!, { select: select }),
});

export const cldr = createCldr({
  lazy: false,
  locales: ["en","en-GB","de","fr","ar"] as const,
  packs: { "en": en, "en-GB": enGB, "de": de, "fr": fr, "ar": ar, "en-001": en001 },
  build,
});
