// Generated by @phensley/cldr-generate — do not edit. Regenerate with pnpm generate:client.

import { createCldr, makeCurrencyFactory, makeDecimalFactory } from '@phensley/cldr';
import { format } from '@phensley/cldr/currency/format';
import { fractionDigits } from '@phensley/cldr/currency/fraction-digits';
import { symbol } from '@phensley/cldr/currency/symbol';
import { compare } from '@phensley/cldr/decimal/compare';
import { scientific } from '@phensley/cldr/decimal/format/scientific';
import { min } from '@phensley/cldr/decimal/min';

const decimal = makeDecimalFactory({
  compare: compare,
  min: min,
  format: { scientific: scientific },
});

import type { DecodedLocalePack } from '@phensley/cldr';
import { en } from '@phensley/cldr/packs/en';
import { es419 } from '@phensley/cldr/packs/es419';
import { fr } from '@phensley/cldr/packs/fr';

const build = (pack: DecodedLocalePack | undefined) => ({
  decimal,
  currency: makeCurrencyFactory(pack!, { format: format, symbol: symbol, fractionDigits: fractionDigits }),
});

export const cldr = createCldr({
  lazy: false,
  locales: ["en","es-419","fr"] as const,
  packs: { "en": en, "es-419": es419, "fr": fr },
  build,
});
