/**
 * Render compiled packs as literal TS data modules (the "pack TS modules,
 * one per locale" deliverable). Output is deterministic: key order comes
 * from compile-time construction order, so regenerating is idempotent and
 * the freshness test can diff committed output against a fresh render.
 */
import type { LocalePack, NumericPack } from './pack/types.js';

export const HEADER = '// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.\n';

/** Locale tag → safe identifier + file stem ('es-419' → 'es419'). */
export const localeIdentifier = (locale: string): string => locale.replace(/[^a-zA-Z0-9]/g, '');

/** File stem → locale tag (inverse): 'es419' → 'es-419', 'enAU' → 'en-AU', 'de' → 'de'. */
export const tagFromStem = (stem: string): string => {
  const m = /^([a-z]{2,3})(?=[A-Z0-9])(.+)$/.exec(stem);
  return m === null ? stem : `${m[1]}-${m[2]}`;
};

const PACK_TYPE_IMPORT = "\nimport type { LocalePack } from '@cldr/internal-core';\n";

export const renderLocaleModule = (locale: string, pack: LocalePack): string =>
  `${HEADER}${PACK_TYPE_IMPORT}export const ${localeIdentifier(locale)}: LocalePack = ${JSON.stringify(pack, null, 2)};\n`;

export const renderNumericModule = (numeric: NumericPack): string =>
  `${HEADER}\nimport type { NumericPack } from '@cldr/internal-core';\n\nexport const numeric: NumericPack = ${JSON.stringify(numeric, null, 2)};\n`;

/**
 * Aggregate module mapping every locale tag to its pack, e.g.:
 *   export const packs: Record<string, LocalePack> = { en, fr, de, 'es-419': es419 };
 */
export const renderPacksModule = (locales: string[]): string => {
  const lines = locales.map((l) => `${JSON.stringify(l)}: ${localeIdentifier(l)}`);
  return `${HEADER}${PACK_TYPE_IMPORT}${locales.map((l) => `import { ${localeIdentifier(l)} } from './${localeIdentifier(l)}.js';`).join('\n')}\n\nexport const packs: Record<string, LocalePack> = { ${lines.join(', ')} };\n`;
};

/** Barrel over the generated dir. */
export const renderIndexModule = (): string =>
  `${HEADER}
export * from './packs.js';
export * from './numeric.js';
`;
