/**
 * The FULL-universe build (publish path; milestone 2 of the coverage
 * workstream, plans/real-cldr-compiler.md §5).
 *
 *   pnpm build:full
 *
 * 1. Runs the normal build (rollup over src — the 11-locale regression
 *    world stays the repo state).
 * 2. Injects the FULL universe into dist: all 766 packs + 443 family
 *    deltas + layout + zones (compiled from the sha-pinned cache —
 *    deterministic; provenance is the gate, coverage.sha256 anchors
 *    compiler drift), and the FULL manifest (dist/manifest.js + .d.ts)
 *    listing every locale — the published package can serve ANY locale;
 *    lazy mode maps all of them.
 *
 * The repo/committed state is untouched: generated-full/ is gitignored,
 * the committed manifest stays the 11 (regression corpus).
 */
import { spawnSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileDataset, localeIdentifier } from '../internal/data-pipeline/src/index.js';
import { buildVariantDelta, pickFamilyBase } from '../internal/data-pipeline/src/compile/delta.js';
import { realCldr } from '../internal/data-pipeline/src/dataset/real.js';
import { deriveManifest, renderManifest, renderManifestConst } from './scan-manifest.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'packages', 'cldr', 'dist');

const HEADER = '// Generated by pnpm build:full (scripts/build-full.ts) — do not edit.\n';

const jsModule = (name: string, value: unknown): string => `${HEADER}export const ${name} = ${JSON.stringify(value, null, 2)};\n`;

const PACK_DTS = (stem: string) => `import { LocalePack } from '../index.js';\n\ndeclare const ${stem}: LocalePack;\n\nexport { ${stem} };\n`;
const DELTA_DTS = (stem: string) => `import { VariantDelta } from '../../_core/pack/types.js';\n\ndeclare const ${stem}: VariantDelta;\n\nexport { ${stem} };\n`;
const LAYOUT_DTS = `declare const layout: Record<string, { kind: 'full' } | { kind: 'delta'; base: string }>;\n\nexport { layout };\n`;
const ZONES_DTS = `import { ZonesTable } from '../_core/pack/types.js';\n\ndeclare const zones: ZonesTable;\n\nexport { zones };\n`;

// 1. normal build
const b = spawnSync('pnpm', ['build'], { cwd: ROOT, stdio: 'inherit' });
if (b.status !== 0) {
  process.exit(b.status ?? 1);
}

// 2. full universe
const dataset = realCldr({ full: true });
const compiled = compileDataset(dataset);
const tags = Object.keys(compiled.locale).sort();

const packsDir = join(DIST, 'packs');
mkdirSync(join(packsDir, 'delta'), { recursive: true });
for (const tag of tags) {
  const stem = localeIdentifier(tag);
  writeFileSync(join(packsDir, `${stem}.js`), jsModule(stem, compiled.locale[tag]));
  writeFileSync(join(packsDir, `${stem}.d.ts`), PACK_DTS(stem));
}

// families + deltas + layout
const layout: Record<string, { kind: 'full' } | { kind: 'delta'; base: string }> = {};
for (const tag of tags) {
  layout[tag] = { kind: 'full' };
}
const families = new Map<string, string[]>();
for (const tag of tags) {
  families.set(tag.split('-')[0], [...(families.get(tag.split('-')[0]) ?? []), tag]);
}
for (const members of families.values()) {
  if (members.length < 2) {
    continue;
  }
  const base = pickFamilyBase(members, dataset.locales);
  for (const tag of members) {
    if (tag === base) {
      continue;
    }
    const delta = buildVariantDelta(dataset.locales[base], dataset.locales[tag], compiled.locale[base].pool);
    delta.base = base;
    const stem = localeIdentifier(tag);
    writeFileSync(join(packsDir, 'delta', `${stem}.js`), jsModule(stem, delta));
    writeFileSync(join(packsDir, 'delta', `${stem}.d.ts`), DELTA_DTS(stem));
    layout[tag] = { kind: 'delta', base };
  }
}
writeFileSync(join(packsDir, 'layout.js'), jsModule('layout', layout));
writeFileSync(join(packsDir, 'layout.d.ts'), LAYOUT_DTS);

// zones companion — reuse the full generation's artifact (packU16 applied)
const fullZones = (await import('../internal/data-pipeline/generated-full/zones.js')).zones;
writeFileSync(join(packsDir, 'zones.js'), jsModule('zones', fullZones));
writeFileSync(join(packsDir, 'zones.d.ts'), ZONES_DTS);

// full manifest: dist/manifest.js (value) + manifest.d.ts (types + value)
const full = deriveManifest({ universe: tags });
writeFileSync(join(DIST, 'manifest.js'), renderManifestConst(full));
writeFileSync(join(DIST, 'manifest.d.ts'), renderManifest(full));

console.log(`build:full — ${tags.length} packs, ${[...families.values()].filter((m) => m.length >= 2).length} families, ${Object.keys(layout).length} layout entries → dist`);
console.log(`build:full — manifest.locales = ${full.locales.length}`);
