/**
 * Regenerate the committed pack assets:
 *
 *   pnpm generate:packs
 *
 * v1 (real data): input is the CLDR 48.2.1 adapter (`realCldr()`, see
 * plans/real-cldr-compiler.md) — the mini-cldr fixture stays for the
 * offline pipeline tests. Pools ship as array literals; only numeric
 * streams go through the codec chain. Deterministic: regenerating after
 * an unchanged dataset produces no diff. The generated files are
 * committed; __tests__/generated.test.ts asserts they stay fresh.
 */
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  compileDataset,
  localeIdentifier,
  packU16,
  renderIndexModule,
  renderLocaleModule,
  renderNumericModule,
  renderPacksModule,
} from '../internal/data-pipeline/src/index.js';
import { buildVariantDelta, pickFamilyBase } from '../internal/data-pipeline/src/compile/delta.js';
import { realCldr } from '../internal/data-pipeline/src/dataset/real.js';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outDirs = [
  join(scriptDir, '../internal/data-pipeline/generated'),
  join(scriptDir, '../packages/cldr/src/packs'),
];

const DELTA_HEADER = "// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.\n\nimport type { VariantDelta } from '@cldr/internal-core';\n";
const LAYOUT_HEADER = "// Generated by pnpm generate:packs (scripts/generate-packs.ts) — do not edit.\n";

const dataset = realCldr();
const compiled = compileDataset(dataset);
const stems = new Set(Object.keys(compiled.locale).map(localeIdentifier));

// ---------------------------------------------------------------------------
// family layout: group by language subtag; base = min pairwise distance;
// every other member ships a sparse delta module + a layout registry entry
// (the generator's config-scoped selection reads this).

const tags = Object.keys(compiled.locale).sort();
const families = new Map<string, string[]>();
for (const tag of tags) {
  const lang = tag.split('-')[0];
  const members = families.get(lang) ?? [];
  members.push(tag);
  families.set(lang, members);
}

const layout: Record<string, { kind: 'full' } | { kind: 'delta'; base: string }> = {};
const deltaStems = new Set<string>();
for (const tag of tags) {
  layout[tag] = { kind: 'full' };
}
for (const members of families.values()) {
  if (members.length < 2) {
    continue;
  }
  const base = pickFamilyBase(members, dataset.locales);
  for (const tag of members) {
    if (tag === base) {
      continue;
    }
    const delta = buildVariantDelta(dataset.locales[base], dataset.locales[tag], compiled.locale[base].pool);
    delta.base = base;
    const module = `${DELTA_HEADER}export const ${localeIdentifier(tag)}: VariantDelta = ${JSON.stringify(delta, null, 2)};\n`;
    for (const outDir of outDirs) {
      mkdirSync(join(outDir, 'delta'), { recursive: true });
      writeFileSync(join(outDir, 'delta', `${localeIdentifier(tag)}.ts`), module);
    }
    deltaStems.add(localeIdentifier(tag));
    layout[tag] = { kind: 'delta', base };
    console.log(`generate-packs: delta ${tag} → base ${base}`);
  }
}

// ---------------------------------------------------------------------------
// zone-offset table (the deferred unit+offset numeric header, design doc
// §2.4): platform tzdb at a fixed instant, 900s units + bias 50 (the
// measured rule; exact for every modern tzdb offset). Committed + frozen;
// a tzdb update on this machine flips it on regenerate (recorded).
const zones = (() => {
  const keys = Intl.supportedValuesOf('timeZone').sort();
  const fmt = new Intl.DateTimeFormat('en-US', { timeZone: 'UTC', timeZoneName: 'longOffset' });
  void fmt;
  const offsets: number[] = [];
  for (const zone of keys) {
    const parts = new Intl.DateTimeFormat('en-US', { timeZone: zone, timeZoneName: 'longOffset' }).formatToParts(new Date('2025-01-15T12:00:00Z'));
    const name = parts.find((p) => p.type === 'timeZoneName')?.value ?? 'GMT';
    const m = /^GMT([+-])(\d{1,2})(?::(\d{2}))?/.exec(name);
    let secs = 0;
    if (m !== null) {
      secs = (Number(m[2]) * 60 + (m[3] ? Number(m[3]) : 0)) * 60 * (m[1] === '-' ? -1 : 1);
    }
    offsets.push(Math.round(secs / 900) + 50);
  }
  return { keys, unit: 900, bias: 50, values: packU16(offsets) };
})();
const zonesModule = `${LAYOUT_HEADER}\nimport type { ZonesTable } from '@cldr/internal-core';\n\nexport const zones: ZonesTable = ${JSON.stringify(zones, null, 2)};\n`;
for (const outDir of outDirs) {
  writeFileSync(join(outDir, 'zones.ts'), zonesModule);
}
console.log(`generate-packs: zones table — ${zones.keys.length} zones, unit ${zones.unit}s, bias ${zones.bias}`);

const layoutModule = `${LAYOUT_HEADER}\nexport const layout: Record<string, { kind: 'full' } | { kind: 'delta'; base: string }> = ${JSON.stringify(layout, null, 2)};\n`;
for (const outDir of outDirs) {
  writeFileSync(join(outDir, 'layout.ts'), layoutModule);
}

for (const outDir of outDirs) {
  mkdirSync(outDir, { recursive: true });
  for (const [locale, pack] of Object.entries(compiled.locale)) {
    writeFileSync(join(outDir, `${localeIdentifier(locale)}.ts`), renderLocaleModule(locale, pack));
  }
  writeFileSync(join(outDir, 'numeric.ts'), renderNumericModule(compiled.numeric));
  // remove stale locale stems (locale-set changes must not leave ghosts:
  // the scanner derives manifest.locales from this dir)
  for (const f of readdirSync(outDir)) {
    if (!f.endsWith('.ts')) {
      continue;
    }
    const stem = f.replace(/\.ts$/, '');
    if (stem !== 'numeric' && stem !== 'packs' && stem !== 'index' && stem !== 'layout' && stem !== 'zones' && !stems.has(stem)) {
      rmSync(join(outDir, f));
      console.log(`generate-packs: removed stale ${join(outDir, f)}`);
    }
  }
  // stale delta modules (family changes must not leave ghosts)
  const deltaDir = join(outDir, 'delta');
  if (existsSync(deltaDir)) {
    for (const f of readdirSync(deltaDir)) {
      if (f.endsWith('.ts') && !deltaStems.has(f.replace(/\.ts$/, ''))) {
        rmSync(join(deltaDir, f));
        console.log(`generate-packs: removed stale delta ${join(deltaDir, f)}`);
      }
    }
  }
}
// pipeline keeps the aggregate modules (its own artifact); the runtime
// package addresses packs per-locale through its exports map instead
const outDir = outDirs[0];
writeFileSync(join(outDir, 'packs.ts'), renderPacksModule(Object.keys(compiled.locale)));
writeFileSync(join(outDir, 'index.ts'), renderIndexModule());

console.log(`generated ${Object.keys(compiled.locale).length} locale packs + numeric (pool arrays) → ${outDirs.join(', ')}`);
