/**
 * Full-universe pack generation (coverage milestone 1; the publish-time
 * flow wires these into dist in milestone 2).
 *
 *   pnpm generate:packs:full
 *
 * Compiles EVERY cached locale (766) and writes the per-locale pack
 * modules into the GITIGNORED generated-full/ directory, plus a
 * deterministic aggregate SHA-256 into the committed
 * internal/data-pipeline/generated/coverage.sha256 (the freshness
 * anchor: with the pinned cldr-json input and a deterministic compiler,
 * the full set is reproducible — the anchor catches compiler drift;
 * source drift is guarded by the sha-pinned fetch).
 *
 * The committed 11-locale regression corpus (generate:packs) is
 * untouched; the full set is breadth, generated on demand.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileDataset, localeIdentifier, packU16, renderLocaleModule } from '../internal/data-pipeline/src/index.js';
import { buildVariantDelta, pickFamilyBase } from '../internal/data-pipeline/src/compile/delta.js';
import { realCldr } from '../internal/data-pipeline/src/dataset/real.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'internal', 'data-pipeline', 'generated-full');
const ANCHOR = join(ROOT, 'internal', 'data-pipeline', 'generated', 'coverage.sha256');
const HEADER = '// Generated by pnpm generate:packs:full (scripts/generate-packs-full.ts) — do not edit.\n';

const dataset = realCldr({ full: true });
const compiled = compileDataset(dataset);
mkdirSync(OUT, { recursive: true });

const tags = Object.keys(compiled.locale).sort();
const write = (rel: string, text: string): void => {
  mkdirSync(join(OUT, dirname(rel)), { recursive: true });
  writeFileSync(join(OUT, rel), text);
};

// ---------------------------------------------------------------------------
// per-locale full packs

for (const tag of tags) {
  write(`${localeIdentifier(tag)}.ts`, renderLocaleModule(tag, compiled.locale[tag]));
}

// ---------------------------------------------------------------------------
// families: base + per-variant deltas + layout registry (mirror generate-packs)

const layout: Record<string, { kind: 'full' } | { kind: 'delta'; base: string }> = {};
const deltaStems = new Set<string>();
for (const tag of tags) {
  layout[tag] = { kind: 'full' };
}
const families = new Map<string, string[]>();
for (const tag of tags) {
  const lang = tag.split('-')[0];
  families.set(lang, [...(families.get(lang) ?? []), tag]);
}
for (const members of families.values()) {
  if (members.length < 2) {
    continue;
  }
  const base = pickFamilyBase(members, dataset.locales);
  for (const tag of members) {
    if (tag === base) {
      continue;
    }
    const delta = buildVariantDelta(dataset.locales[base], dataset.locales[tag], compiled.locale[base].pool);
    delta.base = base;
    write(`delta/${localeIdentifier(tag)}.ts`, `${HEADER}import type { VariantDelta } from '@cldr/internal-core';\n\nexport const ${localeIdentifier(tag)}: VariantDelta = ${JSON.stringify(delta, null, 2)};\n`);
    deltaStems.add(localeIdentifier(tag));
    layout[tag] = { kind: 'delta', base };
  }
}
const familiesCount = [...families.values()].filter((m) => m.length >= 2).length;
write('layout.ts', `${HEADER}\nexport const layout: Record<string, { kind: 'full' } | { kind: 'delta'; base: string }> = ${JSON.stringify(layout, null, 2)};\n`);

// ---------------------------------------------------------------------------
// zones (unit+offset numeric header; platform tzdb at a fixed instant)

const zones = (() => {
  const keys = Intl.supportedValuesOf('timeZone').sort();
  const offsets: number[] = [];
  for (const zone of keys) {
    const parts = new Intl.DateTimeFormat('en-US', { timeZone: zone, timeZoneName: 'longOffset' }).formatToParts(new Date('2025-01-15T12:00:00Z'));
    const name = parts.find((p) => p.type === 'timeZoneName')?.value ?? 'GMT';
    const m = /^GMT([+-])(\d{1,2})(?::(\d{2}))?/.exec(name);
    let secs = 0;
    if (m !== null) {
      secs = (Number(m[2]) * 60 + (m[3] ? Number(m[3]) : 0)) * 60 * (m[1] === '-' ? -1 : 1);
    }
    offsets.push(Math.round(secs / 900) + 50);
  }
  return { keys, unit: 900, bias: 50, values: packU16(offsets) };
})();
write('zones.ts', `${HEADER}import type { ZonesTable } from '@cldr/internal-core';\n\nexport const zones: ZonesTable = ${JSON.stringify(zones, null, 2)};\n`);

// ---------------------------------------------------------------------------
// whole-tree deterministic anchor

const sha = createHash('sha256');
const walk = (dir: string, prefix: string): string[] => {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    const rel = prefix + entry.name;
    if (entry.isDirectory()) {
      files.push(...walk(join(dir, entry.name), rel + '/'));
    } else {
      files.push(rel);
    }
  }
  return files;
};
const files = walk(OUT, '');
for (const rel of files) {
  sha.update(rel + '\0');
  sha.update(readFileSync(join(OUT, rel)));
}
const digest = sha.digest('hex');
writeFileSync(ANCHOR, `${digest}\n`);

console.log(`generate-packs-full: ${tags.length} locales, ${familiesCount} families, ${deltaStems.size} deltas, ${files.length} files → ${OUT}`);
console.log(`generate-packs-full: coverage anchor ${digest} → ${ANCHOR}`);
