// Generated by @phensley/cldr-generate — do not edit. Regenerate with pnpm generate:client.

import { createCldr, makeCurrencyFactory, makeDecimalFactory } from '@phensley/cldr';
import type { Cldr } from '@phensley/cldr';
import { format } from '@phensley/cldr/currency/format';
import { fractionDigits } from '@phensley/cldr/currency/fraction-digits';
import { symbol } from '@phensley/cldr/currency/symbol';
import { scientific } from '@phensley/cldr/decimal/format/scientific';
import { min } from '@phensley/cldr/decimal/min';

const decimal = makeDecimalFactory({
  min: min,
  format: { scientific: scientific },
});

import type { DecodedLocalePack } from '@phensley/cldr';

const build = (pack: DecodedLocalePack | undefined) => ({
  decimal,
  currency: makeCurrencyFactory(pack!, { format: format, symbol: symbol, fractionDigits: fractionDigits }),
});

const client = createCldr({
  lazy: true,
  locales: ["en","fr","de","es-419"] as const,
  packs: { "en": () => import('@phensley/cldr/packs/en').then((m) => m.en), "fr": () => import('@phensley/cldr/packs/fr').then((m) => m.fr), "de": () => import('@phensley/cldr/packs/de').then((m) => m.de), "es-419": () => import('@phensley/cldr/packs/es419').then((m) => m.es419) },
  build,
});

export const cldr: Cldr<string, ReturnType<typeof build>> = {
  get(locale) {
    return client.get(locale as "en" | "fr" | "de" | "es-419");
  },
  preload(locale) {
    return client.preload(locale as "en" | "fr" | "de" | "es-419");
  },
};
