// Generated by @phensley/cldr-generate — do not edit. Regenerate with pnpm generate:client.

import { createCldr, makeCurrencyFactory, makeDecimalFactory } from '@phensley/cldr';
import type { Cldr } from '@phensley/cldr';
import { format } from '@phensley/cldr/currency/format';
import { fractionDigits } from '@phensley/cldr/currency/fraction-digits';
import { symbol } from '@phensley/cldr/currency/symbol';
import { scientific } from '@phensley/cldr/decimal/format/scientific';
import { min } from '@phensley/cldr/decimal/min';

const decimal = makeDecimalFactory({
  min: min,
  format: { scientific: scientific },
});

import type { DecodedLocalePack } from '@phensley/cldr';

const build = (pack: DecodedLocalePack | undefined) => ({
  decimal,
  currency: makeCurrencyFactory(pack!, { format: format, symbol: symbol, fractionDigits: fractionDigits }),
});

const client = createCldr({
  lazy: true,
  locales: ["ar","de","en","en-001","en-AU","en-CA","en-GB","fr","hi","ru","zh"] as const,
  packs: { "ar": () => import('@phensley/cldr/packs/ar').then((m) => m.ar), "de": () => import('@phensley/cldr/packs/de').then((m) => m.de), "en": () => import('@phensley/cldr/packs/delta/en').then((m) => m.en), "en-001": () => import('@phensley/cldr/packs/en001').then((m) => m.en001), "en-AU": () => import('@phensley/cldr/packs/delta/enAU').then((m) => m.enAU), "en-CA": () => import('@phensley/cldr/packs/delta/enCA').then((m) => m.enCA), "en-GB": () => import('@phensley/cldr/packs/delta/enGB').then((m) => m.enGB), "fr": () => import('@phensley/cldr/packs/fr').then((m) => m.fr), "hi": () => import('@phensley/cldr/packs/hi').then((m) => m.hi), "ru": () => import('@phensley/cldr/packs/ru').then((m) => m.ru), "zh": () => import('@phensley/cldr/packs/zh').then((m) => m.zh) },
  build,
});

export const cldr: Cldr<string, ReturnType<typeof build>> = {
  get(locale) {
    return client.get(locale as "ar" | "de" | "en" | "en-001" | "en-AU" | "en-CA" | "en-GB" | "fr" | "hi" | "ru" | "zh");
  },
  preload(locale) {
    return client.preload(locale as "ar" | "de" | "en" | "en-001" | "en-AU" | "en-CA" | "en-GB" | "fr" | "hi" | "ru" | "zh");
  },
};
